version: '3'

services:
  website:
    image: chatfrc
    build:
      context: .
      dockerfile: Dockerfile
    user: 'node'
    environment:
      - NODE_ENV=production
      - TZ=US/Pacific
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3000:3000

  qdrantdb:
    image: 'qdrant/qdrant'
    container_name: 'qdrantdb'
    ports:
      - 6333:6333
      - 6334:6334
